### ISSUE TITLE
Blynk.tweet not working on Particle

### ISSUE THREAD

**Issue by RBrouns** [vshymanskyy/blynk-library-particle#11]
See the following forum post for more info:
https://community.blynk.cc/t/blynk-tweet-not-working-with-particle-photon/24754/16

Issue observed on **0.5.1**.
Also attempted 0.5.0, 0.4.10, did not work.

**Comment by vshymanskyy** [comment]
Please try with the latest library.
If you still have issues, please post to https://community.blynk.cc
