### ISSUE TITLE
Not able to connect to local server

### ISSUE THREAD

**Issue by tauchmi** [vshymanskyy/blynk-library-particle#14]
Hello,

I do have the same problem as described in the following particle post

https://community.particle.io/t/photon-code-does-not-work-on-blynk-local-server/51128

Any idea what the problem is here? I can access the blynk server with other NodeMcu and Wemos D1 mini without any issues.

Thanks in advance.

**Comment by craftyshark** [comment]
I have a silly idea, try taking out the 8080 at the end, just put the auth and IP address. Does that make any difference?

**Comment by tauchmi** [comment]
I'm not using this device and library anymore, sorry.

**Comment by craftyshark** [comment]
OOF. Go ahead and close this issue for now pls. If someone else has it, they'll post it
