### ISSUE TITLE
BLESerial is not defined in the example

### ISSUE THREAD

**Issue by markwkiehl** [vshymanskyy/blynk-library-particle#17]
BLESerial is not defined in the example.  Lots of other people confused by this.  I'm looking for a Blynk BLE example that works with nRF52 (Particle Argon/Boron).

**Comment by vshymanskyy** [comment]
Particle Argon/Boron do not use BLESerial to communicate to the BLE peripheral. It requires a more complex implementation (i.e. it is not available yet)
